name: Run Unit Tests

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The environment to run the pipeline on

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python (use the version that matches your project)
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust to match your Python version

    # Step 3: Install dependencies (make sure your 'requirements.txt' is in the root of the repository)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install the packages from your requirements.txt

    # Step 4: Run unit tests (assuming you're using pytest)
    - name: Run unit tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests, stop at first failure, suppress warnings, and reduce output verbosity
